### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by jia0511** [Linaom1214/tensorrt-python#17]
HI，

我按照你的流程安装环境后，报了以下问题，我的环境python3.8, tensorRT版本nvidia_tensorrt-8.4.1.5-cp38-none-linux_x86_64.whl

`python trt.py 
[07/31/2022-16:12:30] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReader::35] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 0, Serialized Engine Version: 43)
[07/31/2022-16:12:30] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "trt.py", line 28, in <module>
    pred = Predictor(engine_path='../yolov7-nms.trt')
  File "trt.py", line 13, in __init__
    super(Predictor, self).__init__(engine_path)
  File "/home/jack/data1/project/tensorrt-python/yolov7/../utils/utils.py", line 29, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
`

**Comment by LeonNerd** [comment]
我也有同样问题

**Comment by Xintianbyz** [comment]
我也是

**Comment by Linaom1214** [comment]
```
Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match
```
序列化和反序列的版本应该一致
