### ISSUE TITLE
在利用trt文件推理时，遇到了一个错误

### ISSUE THREAD

**Issue by yun9993** [Linaom1214/tensorrt-python#27]
(yolo) D:\hskj\code\tensorrt-python-main\yolov7>python trt.py
[08/11/2022-17:42:29] [TRT] [E] 1: [pluginV2Runner.cpp::nvinfer1::rt::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[08/11/2022-17:42:29] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "trt.py", line 21, in <module>
    pred = Predictor(engine_path='D:/hskj/code/tensorrt-python-main/v7_last.engine')
  File "trt.py", line 13, in __init__
    super(Predictor, self).__init__(engine_path)
  File "D:\hskj\code\tensorrt-python-main\yolov7\..\utils\utils.py", line 22, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute '

请问这个是我模型转换的不对么？

**Comment by Linaom1214** [comment]
> 

你的onnx模型是怎么导出的呢？

**Comment by Linaom1214** [comment]
参考 https://github.com/Linaom1214/tensorrt-python/issues/12#issuecomment-1211769328

**Comment by yun9993** [comment]
> 

对的呀，我用官方的export转的onnx，用你的export转的trt。模型是我自己训练的，不知道是模型的问题还是我推理环境的问题

**Comment by Linaom1214** [comment]
> 

官方的那个教程有点问题， 我猜测你是使用了 端到端模型 建议更新代码， 使用我今天更新的版本重新生成

**Comment by pcb9382** [comment]
python
step1:
          python WongKinYiu/yolov7/export.py --weights ./yolov7-tiny.pt --grid  --simplify
step2:
         python Linaom1214/tensorrt-python/export.py -o /content/yolov7/yolov7-tiny.onnx -e ./yolov7-tiny-nms.trt -p fp16 --end2end 

python3 trt.py
[08/12/2022-18:57:03] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.2.1
[08/12/2022-18:57:03] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.2.1
/home/pcb/.local/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "trt.py", line 30, in <module>
    origin_img = pred.inference(img_path, conf=0.3)
  File "../utils/utils.py", line 99, in inference
    predictions = np.reshape(data, (1, -1, int(5+self.n_classes)))[0]
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/pcb/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/pcb/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/pcb/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 4 into shape (1,newaxis,85)


C++也有问题

**Comment by Linaom1214** [comment]
> 
大家先读一下文档！  



cd yolov7
python trt.py
tips!

if you use the end2end model please modift the code as such

origin_img = pred.inference(img_path, conf=0.5, end2end=True)
